BIN_NAME=gaiad
COSMOS_TOP=${GOPATH}/src/github.com/cosmos/cosmos-sdk
COSMOS_BIN=${GOPATH}/bin
COSMOS_NET_TOP=`pwd`
COSMOS_NET_CACHE=${COSMOS_NET_TOP}/cache

BASE_PORT_PREFIX=10000
P2P_PORT_SUFFIX=56
let RPC_PORT_SUFFIX=${P2P_PORT_SUFFIX}+1
let BASE_PORT=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedp2pport=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedrpcport=${BASE_PORT_PREFIX}+${RPC_PORT_SUFFIX}
